color: orange
fieldLayouts:
  0555d587-c1cc-4f76-8892-b369d6d0a178:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'This page is for changing information about Backyard University'
            label: About
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3c384b38-27ec-43bb-bf4c-270aa75b6977
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb8918ee-8e0f-44e0-9067-15f06fca63ff # content builder CK
            handle: null
            includeInCards: false
            instructions: null
            label: 'About CKEditor'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04423dbe-6709-4e19-9c2b-486173e1390a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc9dd224-a899-452b-9150-9e9f94db2da3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 90308854-296d-4a84-a1a0-8579ecc3ecd1 # images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b0688e9-c660-4c20-bb46-dc60da94a21c
            userCondition: null
            warning: null
            width: 100
        name: images
        uid: 177c9863-2167-48f8-a7dd-d88bd99295b2
        userCondition: null
handle: about
hasTitleField: true
icon: acorn
name: about
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
