color: green
fieldLayouts:
  a1ef2840-9118-4b4a-b862-d9a363890d41:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Class Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 48c21944-87b1-427e-ae21-ebcadd4decef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a1ceb67-8702-4d71-ab27-c1ce54eeedb5 # single line plaintext
            handle: dateTime
            includeInCards: false
            instructions: 'Class day, date, start time, and end time: Saturday, October 21, 2023, 10:30am - 12:30pm'
            label: 'date & time'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d9f2711-60a2-4314-93e2-3e02f49011e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a1ceb67-8702-4d71-ab27-c1ce54eeedb5 # single line plaintext
            handle: location
            includeInCards: false
            instructions: null
            label: location
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 391e8e37-6ec1-42cb-ac58-b16e0985196f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 277cebc1-e5f9-4f08-a729-1ed4feaa3cfb # Text Link
            handle: locationLink
            includeInCards: false
            instructions: 'map link, website, etc.'
            label: 'location link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa0e3450-f3db-4dfe-a96a-47314d81da98
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6879c3a2-493c-4b4f-941b-13799c080848 # plaintext-multiline
            handle: shortDescription
            includeInCards: false
            instructions: null
            label: 'short class description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5eff5625-747f-41c4-bcd4-70b45bfe1c8e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6365fd4a-8b7d-4e60-a260-0e998504e818 # image
            handle: images
            includeInCards: false
            instructions: null
            label: images
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8defc2d3-57f0-4d29-a9d6-b224c97ddab4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb8918ee-8e0f-44e0-9067-15f06fca63ff # CKEditor
            handle: classDescription
            includeInCards: false
            instructions: null
            label: 'Class Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff30f52a-e302-4576-b2e2-bfaba18fe9de
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ddd1978f-309c-4f47-a7f1-45370444142f # class cost
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 837bbcb1-0b97-4df8-8124-f14f5f753222
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 734d4095-bd96-4d2a-ad75-084d7befc967 # Instructor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4853629d-9e05-4023-af89-ed6552a95aca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a533e4ec-7cbe-4a9b-8723-acd90ff3aa26
        userCondition: null
handle: classes
hasTitleField: true
icon: tomato
name: Classes
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
