color: yellow
fieldLayouts:
  e8bd697c-b079-491b-8a24-8504f5d7c883:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: coaching
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2b1af2e6-f585-4e3c-8fff-56b5618c3d22
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb8918ee-8e0f-44e0-9067-15f06fca63ff # content builder CK
            handle: coaching
            includeInCards: false
            instructions: 'This page is for editing coaching info.'
            label: coaching
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f705ee3-6e58-410f-b32e-4b94db90f9f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c68b2b74-740e-489f-b338-33022d86b3d6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 90308854-296d-4a84-a1a0-8579ecc3ecd1 # images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6f62f5a-8acc-4211-84b8-b3e28d545113
            userCondition: null
            warning: null
            width: 100
        name: images
        uid: ce67454d-57c0-40c3-8285-3cff793bfcf7
        userCondition: null
handle: coaching
hasTitleField: true
icon: spa
name: coaching
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
