color: yellow
fieldLayouts:
  391d98c6-8890-4b00-872d-f372e0a712e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 968dab38-9fb9-491d-8888-1c05677d37f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 277cebc1-e5f9-4f08-a729-1ed4feaa3cfb # Text Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6df3b6e5-0bdf-441d-b2c0-86f0e1d7a4c6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 35e062fc-ce7a-4720-8d79-5ce20e9745fa
        userCondition: null
handle: cta
hasTitleField: false
icon: bullseye
name: CTA
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
