color: emerald
fieldLayouts:
  011dec44-218c-4833-9d09-1750762404ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e99aca5-1973-43d7-b694-6b93682ecb8b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c9699d9-6b10-462d-b29d-0f55051ded8f # Simple Table
            handle: classDetails
            includeInCards: false
            instructions: null
            label: 'Class Details'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ba0584e-ad62-4065-80b5-d73e55a82e51
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2e50d571-20aa-4ea5-a81c-5aef0c7f74e8
        userCondition: null
handle: details
hasTitleField: true
icon: asterisk
name: Details
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
