color: indigo
fieldLayouts:
  1af30e65-e29b-451e-a06a-799c70025c4a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9163b098-0fbf-4802-a314-5e7176e27c0a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6365fd4a-8b7d-4e60-a260-0e998504e818 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da8c24d8-e94c-4dc4-91e1-7f7dd5a9ba59
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d754d3b1-54ec-4d6b-bf92-cad90c0ac42b
        userCondition: null
handle: images
hasTitleField: false
icon: camera
name: images
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ entryId }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
