color: pink
fieldLayouts:
  7bba22f1-4661-4324-8938-f7b6e797489c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7b4c27b5-7103-4a74-aa3b-c5af9e78fd7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6365fd4a-8b7d-4e60-a260-0e998504e818 # image
            handle: instructorImage
            includeInCards: false
            instructions: null
            label: 'instructor image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b05923c5-1cc8-4c65-88b4-e741111aabf5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb8918ee-8e0f-44e0-9067-15f06fca63ff # CKEditor
            handle: bio
            includeInCards: false
            instructions: null
            label: bio
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41c83ed7-d329-4db7-b741-e74942f1ef97
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6af3e72a-28f8-436e-a87f-388d973722d3
        userCondition: null
handle: instructor
hasTitleField: true
icon: user
name: instructor
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
