color: pink
fieldLayouts:
  0933576c-90c1-4c73-bf01-c42e6f85b7d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'post title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a5b5d720-d624-4bd6-9943-7340830aba16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 91db173b-0a25-4a07-9d59-d04125e8337e # date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 842321f8-6b19-40e0-aa7c-4566e210f916
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb8918ee-8e0f-44e0-9067-15f06fca63ff # content builder CK
            handle: postContent
            includeInCards: false
            instructions: 'The content of the journal post'
            label: 'post content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c28894ad-eb71-41af-af5b-3bf35cfc897e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9052a5b7-2d86-43b9-8c16-2ad8ef7945a9 # author
            handle: postAuthor
            includeInCards: false
            instructions: null
            label: author
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13489b7e-4e75-4237-9452-dcd8ea002b0e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f72e491f-6bb7-4a54-add8-0f290e88b121
        userCondition: null
handle: post
hasTitleField: true
icon: book
name: post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
