color: sky
fieldLayouts:
  41ee7868-1e6c-47ea-b628-d00f1adc4b50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 431ef587-db0a-43a1-97ae-790e8063c029
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb8918ee-8e0f-44e0-9067-15f06fca63ff # content builder CK
            handle: richTextContent
            includeInCards: false
            instructions: null
            label: 'rich text content'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8224e375-29b7-4c5d-a7e0-07d25fff14d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 365d0649-d5db-4d50-9538-3dea1162cbf9
        userCondition: null
handle: richTextContent
hasTitleField: false
icon: font-case
name: 'rich text content'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{entryId}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
