color: pink
fieldLayouts:
  31e47a47-c4d3-4d23-8c09-ba5454b31bbb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2f711724-0a3f-4c30-8fea-d495d2a13197
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6879c3a2-493c-4b4f-941b-13799c080848 # plaintext-multiline
            handle: linkText
            includeInCards: false
            instructions: null
            label: 'Link Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eb02d0b-914e-494f-9029-a35800d2e503
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 32ceb6f1-4fab-4064-b3da-23186711b4e2 # Url
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3b4f6a2-b096-43bf-ac5b-96cd18019c8f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1b90caf-9926-44f4-b171-58f3d8b16fd0
        userCondition: null
handle: textLink
hasTitleField: false
icon: link
name: TextLink
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{linkText}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
