headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: ckeditor
options:
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
toolbar:
  - heading
  - '|'
  - bulletedList
  - bold
  - italic
  - fontSize
  - link
  - createEntry
