columnSuffix: null
handle: instructor
instructions: null
name: Instructor
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add instructor'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:3156aee6-ecaa-4780-a974-6bc6956fe541' # instructors
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
