columnSuffix: null
handle: time
instructions: null
name: time
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
