dateModified: 1719461679
email:
  fromEmail: racheljlindsay@gmail.com
  fromName: backyard-university
  transportType: craft\mail\transportadapters\Sendmail
fs:
  localDisk:
    hasUrls: true
    name: 'local disk'
    settings:
      path: '@webroot/localDisk'
    type: craft\fs\Local
    url: '@web/localDisk'
  xform:
    hasUrls: true
    name: xform
    settings:
      path: '@webroot/xform'
    type: craft\fs\Local
    url: '@web/xform'
meta:
  __names__:
    3b0e8ab2-2121-4df7-8182-f81606457291: coaching # coaching
    4ab5470b-6f98-46a5-9de7-ae4a7e955034: homepage # homepage
    7c9699d9-6b10-462d-b29d-0f55051ded8f: 'simple Table' # simple Table
    7e20a71f-ae55-4a79-9dec-a555b3c45b93: coaching # coaching
    7f560f57-e2c3-4cf4-9f34-08418c21731f: post # post
    8dc3b801-b9cd-48bd-9f66-d26fbfcfa667: journal # journal
    9a1ceb67-8702-4d71-ab27-c1ce54eeedb5: 'single line plaintext' # single line plaintext
    14bd610e-32c4-4edf-914d-d43bfa32aa82: 'Public Schema' # Public Schema
    30cd7c72-a224-47cc-b110-2b75dd147156: images # images
    32ceb6f1-4fab-4064-b3da-23186711b4e2: Url # Url
    83ff54c4-14e8-4364-ab22-626c8615f0ac: backyard-university # backyard-university
    91db173b-0a25-4a07-9d59-d04125e8337e: date # date
    95de9ce8-1ed9-4d90-8330-a98cdc27fc0e: backyard-university # backyard-university
    277cebc1-e5f9-4f08-a729-1ed4feaa3cfb: 'text link' # text link
    734d4095-bd96-4d2a-ad75-084d7befc967: instructor # instructor
    2104f81d-4950-44be-82ff-b728d5922ac3: Classes # Classes
    2511dad3-82f3-4053-9df2-675b5dc6336d: homepage # homepage
    3156aee6-ecaa-4780-a974-6bc6956fe541: instructors # instructors
    6365fd4a-8b7d-4e60-a260-0e998504e818: image # image
    6879c3a2-493c-4b4f-941b-13799c080848: plaintext-multiline # plaintext-multiline
    9052a5b7-2d86-43b9-8c16-2ad8ef7945a9: author # author
    99708b36-7733-4560-a15f-ac6db90ee838: classes # classes
    262926b3-1484-4cc8-8956-a610c3bef92b: about # about
    853056af-c326-4731-a0cd-fe065d13d97f: ckeditor # ckeditor
    1674726e-694e-4c98-874d-aea4aca0f1c5: 'rich text content' # rich text content
    90308854-296d-4a84-a1a0-8579ecc3ecd1: images # images
    a50c4bce-6e97-4d46-8fb9-c6f75a333e78: Details # Details
    a6877f4d-9055-4da1-a5b1-c4170ac02cd4: instructor # instructor
    ad92d50c-a92c-4306-b30d-16a896560193: 'journal listing' # journal listing
    b2b958cd-3387-41a9-9f93-74fffdb318e6: CTA # CTA
    b7d0e1ff-113f-4452-9b43-525f2ab2cf56: about # about
    cb8918ee-8e0f-44e0-9067-15f06fca63ff: 'content builder CK' # content builder CK
    ccfb8db7-6402-4ae6-ba81-e0cbadeb2508: 'class listing' # class listing
    d189f334-1f56-4f9c-8b27-9862c0607bda: 'listing page' # listing page
    d897fca1-8cdf-48df-9ab9-37e07bf9b10c: images # images
    d449752f-c799-474e-b76e-14a9c8189f9e: Simple # Simple
    ddd1978f-309c-4f47-a7f1-45370444142f: 'class cost' # class cost
    e9b57168-2994-4fbe-98e0-32be8ea9ccdc: time # time
    fc1192e1-8612-4a29-9177-ca5dd3c25733: TextLink # TextLink
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  picture:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: solo
  live: true
  name: backyard-university
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
