defaultPlacement: end
enableVersioning: true
entryTypes:
  - b7d0e1ff-113f-4452-9b43-525f2ab2cf56 # about
handle: about
maxAuthors: 1
name: about
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  83ff54c4-14e8-4364-ab22-626c8615f0ac: # backyard-university
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: about
type: single
