defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2104f81d-4950-44be-82ff-b728d5922ac3 # Classes
handle: classes
maxAuthors: 1
name: classes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  83ff54c4-14e8-4364-ab22-626c8615f0ac: # backyard-university
    enabledByDefault: true
    hasUrls: true
    template: classes/_entry.twig
    uriFormat: 'classes/{slug}'
type: channel
