defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4ab5470b-6f98-46a5-9de7-ae4a7e955034 # homepage
handle: homepage
maxAuthors: 1
name: homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  83ff54c4-14e8-4364-ab22-626c8615f0ac: # backyard-university
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
